version: '3'
services:
  frontend: 
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "80:80"  
    depends_on:
      - backend 
    networks:
      - mynetwork

  backend:
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    env_file:
      - ./back/.env
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
