version: '3'
services:
  frontend:
    build:
      context: ./Front   
      dockerfile: Dockerfile
    ports:
      - "80:80"  
    depends_on:
      - backend 
    networks:
      - mynetwork

  backend:
    build:
      context: ./Back     
      dockerfile: Dockerfile 
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge