name: Backend CI/CD

on:
  push:
    branches:
      - Pr
  pull_request:
    branches:
      - Pr

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: ~/.docker/buildx-cache
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Build Docker image for Backend
        run: |
          docker build -f Back/Dockerfile -t backend:latest .  # Build the backend Docker image using the Dockerfile in the 'Back' folder

      - name: Log in to DockerHub
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin  # Login to DockerHub using GitHub secrets

      - name: Push Docker image to Docker Hub
        run: |
          docker push backend:latest  # Push the backend image to Docker Hub
