name: CI Pipeline

on:
  push:
    branches: [Pr]
  pull_request:
    branches: [pr]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push frontend
        uses: docker/build-push-action@v4
        with:
          context: ${{ github.workspace }}/front
          file: ${{ github.workspace }}/front/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/frontend:${{ github.sha }}

      - name: Build and push backend
        uses: docker/build-push-action@v4
        with:
          context: ${{ github.workspace }}/back
          file: ${{ github.workspace }}/back/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/backend:${{ github.sha }}

      - name: Update Docker Compose file
        run: |
          sed -i 's|build:|image: ${{ secrets.DOCKERHUB_USERNAME }}/frontend:${{ github.sha }}|g' ${{ github.workspace }}/docker-compose.yml
          sed -i 's|build:|image: ${{ secrets.DOCKERHUB_USERNAME }}/backend:${{ github.sha }}|g' ${{ github.workspace }}/docker-compose.yml

      - name: Upload updated docker-compose.yml
        uses: actions/upload-artifact@v4
        with:
          name: docker-compose
          path: ${{ github.workspace }}/docker-compose.yml
