name: Build and Push Docker Images

on:
  push:
    branches:
      - Pr
  pull_request:
    branches:
      - Pr

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Verify directory structure
      - name: Check current working directory and file structure
        run: |
          pwd  # Print current directory
          ls -R  # List all files recursively

      # Ensure Docker Compose is installed
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.18.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      # Use Docker Buildx to enable build caching
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: ~/.docker/buildx-cache
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      # Build the Docker images separately
      - name: Build Docker images
        run: docker-compose build
        working-directory: ${{ github.workspace }}

      # Start the containers
      - name: Start the services
        run: docker-compose up -d
        working-directory: ${{ github.workspace }}

      # Check the status of the running containers
      - name: Check container status
        run: docker-compose ps
        working-directory: ${{ github.workspace }}
