name: CI Pipeline

on:
  push:
    branches: [Pr]
  pull_request:
    branches: [pr]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push combined image
        uses: docker/build-push-action@v4
        with:
          context: ${{ github.workspace }}
          file: ${{ github.workspace }}/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/combined-image:${{ github.sha }}
