name: Build and Push Docker Images

on:
  push:
    branches:
      - Pr
  pull_request:
    branches:
      - Pr

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Step 3: Cache Docker layers to speed up build time
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: ~/.docker/buildx-cache
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      # Step 4: Log in to Docker Hub
      - name: Log in to Docker Hub
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin

      # Step 5: Build and push the backend Docker image
      - name: Build backend Docker image
        run: |
          docker-compose -f docker-compose.yml build backend
          docker-compose -f docker-compose.yml push backend

      # Step 6: Build and push the frontend Docker image
      - name: Build frontend Docker image
        run: |
          docker-compose -f docker-compose.yml build frontend
          docker-compose -f docker-compose.yml push frontend
