name: CI Pipeline

on:
  push:
    branches: [Pr]
  pull_request:
    branches: [Pr]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push frontend
        uses: docker/build-push-action@v2
        with:
          context: ./front
          file: ./front/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/frontend:${{ github.sha }}

      - name: Build and push backend
        uses: docker/build-push-action@v2
        with:
          context: ./back
          file: ./back/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/backend:${{ github.sha }}

      - name: Update Docker Compose file
        run: |
          sed -i 's|build:|image: ${{ secrets.DOCKERHUB_USERNAME }}/frontend:${{ github.sha }}|g' docker-compose.yml
          sed -i 's|build:|image: ${{ secrets.DOCKERHUB_USERNAME }}/backend:${{ github.sha }}|g' docker-compose.yml

      - name: Upload updated docker-compose.yml
        uses: actions/upload-artifact@v2
        with:
          name: docker-compose
          path: docker-compose.yml
